create extension if not exists "uuid-ossp";

create table if not exists "geo"
(
    id UUID unique  not null default uuid_generate_v1() primary key,
    name varchar(255) not null
);

insert into "geo" (id, name) values
(uuid_generate_v1(), 'Австралия'),
(uuid_generate_v1(), 'Австрия'),
(uuid_generate_v1(), 'Азербайджан'),
(uuid_generate_v1(), 'Албания'),
(uuid_generate_v1(), 'Алжир'),
(uuid_generate_v1(), 'Ангола'),
(uuid_generate_v1(), 'Андорра'),
(uuid_generate_v1(), 'Антигуа и Барбуда'),
(uuid_generate_v1(), 'Аргентина'),
(uuid_generate_v1(), 'Армения'),
(uuid_generate_v1(), 'Афганистан'),
(uuid_generate_v1(), 'Багамские Острова'),
(uuid_generate_v1(), 'Бангладеш'),
(uuid_generate_v1(), 'Барбадос'),
(uuid_generate_v1(), 'Бахрейн'),
(uuid_generate_v1(), 'Белиз'),
(uuid_generate_v1(), 'Белоруссия'),
(uuid_generate_v1(), 'Бельгия'),
(uuid_generate_v1(), 'Бенин'),
(uuid_generate_v1(), 'Болгария'),
(uuid_generate_v1(), 'Боливия'),
(uuid_generate_v1(), 'Босния и Герцеговина'),
(uuid_generate_v1(), 'Ботсвана'),
(uuid_generate_v1(), 'Бразилия'),
(uuid_generate_v1(), 'Бруней'),
(uuid_generate_v1(), 'Буркина-Фасо'),
(uuid_generate_v1(), 'Бурунди'),
(uuid_generate_v1(), 'Бутан'),
(uuid_generate_v1(), 'Вануату'),
(uuid_generate_v1(), 'Ватикан'),
(uuid_generate_v1(), 'Великобритания'),
(uuid_generate_v1(), 'Венгрия'),
(uuid_generate_v1(), 'Венесуэла'),
(uuid_generate_v1(), 'Восточный Тимор'),
(uuid_generate_v1(), 'Вьетнам'),
(uuid_generate_v1(), 'Габон'),
(uuid_generate_v1(), 'Гайана'),
(uuid_generate_v1(), 'Гамбия'),
(uuid_generate_v1(), 'Гана'),
(uuid_generate_v1(), 'Гватемала'),
(uuid_generate_v1(), 'Гвинея'),
(uuid_generate_v1(), 'Гвинея-Бисау'),
(uuid_generate_v1(), 'Германия'),
(uuid_generate_v1(), 'Гондурас'),
(uuid_generate_v1(), 'Гренада'),
(uuid_generate_v1(), 'Греция'),
(uuid_generate_v1(), 'Грузия'),
(uuid_generate_v1(), 'Дания'),
(uuid_generate_v1(), 'Демократическая Республика Конго'),
(uuid_generate_v1(), 'Джибути'),
(uuid_generate_v1(), 'Доминика'),
(uuid_generate_v1(), 'Доминиканская Республика'),
(uuid_generate_v1(), 'Египет'),
(uuid_generate_v1(), 'Замбия'),
(uuid_generate_v1(), 'Зимбабве'),
(uuid_generate_v1(), 'Израиль'),
(uuid_generate_v1(), 'Индия'),
(uuid_generate_v1(), 'Индонезия'),
(uuid_generate_v1(), 'Иордания'),
(uuid_generate_v1(), 'Ирак'),
(uuid_generate_v1(), 'Иран'),
(uuid_generate_v1(), 'Ирландия'),
(uuid_generate_v1(), 'Исландия'),
(uuid_generate_v1(), 'Испания'),
(uuid_generate_v1(), 'Италия'),
(uuid_generate_v1(), 'Йемен'),
(uuid_generate_v1(), 'Кабо-Верде'),
(uuid_generate_v1(), 'Казахстан'),
(uuid_generate_v1(), 'Камбоджа'),
(uuid_generate_v1(), 'Камерун'),
(uuid_generate_v1(), 'Канада'),
(uuid_generate_v1(), 'Катар'),
(uuid_generate_v1(), 'Кения'),
(uuid_generate_v1(), 'Киргизия'),
(uuid_generate_v1(), 'Кирибати'),
(uuid_generate_v1(), 'Китай'),
(uuid_generate_v1(), 'Колумбия'),
(uuid_generate_v1(), 'Коморы'),
(uuid_generate_v1(), 'Корейская Народно-Демократическая Республика'),
(uuid_generate_v1(), 'Коста-Рика'),
(uuid_generate_v1(), 'Кот-д’Ивуар'),
(uuid_generate_v1(), 'Куба'),
(uuid_generate_v1(), 'Кувейт'),
(uuid_generate_v1(), 'Лаос'),
(uuid_generate_v1(), 'Латвия'),
(uuid_generate_v1(), 'Лесото'),
(uuid_generate_v1(), 'Либерия'),
(uuid_generate_v1(), 'Ливан'),
(uuid_generate_v1(), 'Ливия'),
(uuid_generate_v1(), 'Литва'),
(uuid_generate_v1(), 'Лихтенштейн'),
(uuid_generate_v1(), 'Люксембург'),
(uuid_generate_v1(), 'Маврикий'),
(uuid_generate_v1(), 'Мавритания'),
(uuid_generate_v1(), 'Мадагаскар'),
(uuid_generate_v1(), 'Малави'),
(uuid_generate_v1(), 'Малайзия'),
(uuid_generate_v1(), 'Мали'),
(uuid_generate_v1(), 'Мальдивы'),
(uuid_generate_v1(), 'Мальта'),
(uuid_generate_v1(), 'Марокко'),
(uuid_generate_v1(), 'Маршалловы Острова'),
(uuid_generate_v1(), 'Мексика'),
(uuid_generate_v1(), 'Мозамбик'),
(uuid_generate_v1(), 'Молдавия'),
(uuid_generate_v1(), 'Монако'),
(uuid_generate_v1(), 'Монголия'),
(uuid_generate_v1(), 'Мьянма'),
(uuid_generate_v1(), 'Намибия'),
(uuid_generate_v1(), 'Науру'),
(uuid_generate_v1(), 'Непал'),
(uuid_generate_v1(), 'Нигер'),
(uuid_generate_v1(), 'Нигерия'),
(uuid_generate_v1(), 'Нидерланды'),
(uuid_generate_v1(), 'Никарагуа'),
(uuid_generate_v1(), 'Новая Зеландия'),
(uuid_generate_v1(), 'Норвегия'),
(uuid_generate_v1(), 'Объединённые Арабские Эмираты'),
(uuid_generate_v1(), 'Оман'),
(uuid_generate_v1(), 'Пакистан'),
(uuid_generate_v1(), 'Палау'),
(uuid_generate_v1(), 'Палестина'),
(uuid_generate_v1(), 'Панама'),
(uuid_generate_v1(), 'Папуа — Новая Гвинея'),
(uuid_generate_v1(), 'Парагвай'),
(uuid_generate_v1(), 'Перу'),
(uuid_generate_v1(), 'Польша'),
(uuid_generate_v1(), 'Португалия'),
(uuid_generate_v1(), 'Республика Гаити'),
(uuid_generate_v1(), 'Республика Кипр'),
(uuid_generate_v1(), 'Республика Конго'),
(uuid_generate_v1(), 'Республика Корея'),
(uuid_generate_v1(), 'Россия'),
(uuid_generate_v1(), 'Руанда'),
(uuid_generate_v1(), 'Румыния'),
(uuid_generate_v1(), 'Сальвадор'),
(uuid_generate_v1(), 'Самоа'),
(uuid_generate_v1(), 'Сан-Марино'),
(uuid_generate_v1(), 'Сан-Томе и Принсипи'),
(uuid_generate_v1(), 'Саудовская Аравия'),
(uuid_generate_v1(), 'Сейшельские Острова'),
(uuid_generate_v1(), 'Сенегал'),
(uuid_generate_v1(), 'Сент-Винсент и Гренадины'),
(uuid_generate_v1(), 'Сент-Китс и Невис'),
(uuid_generate_v1(), 'Сент-Люсия'),
(uuid_generate_v1(), 'Сербия'),
(uuid_generate_v1(), 'Сингапур'),
(uuid_generate_v1(), 'Сирия'),
(uuid_generate_v1(), 'Словакия'),
(uuid_generate_v1(), 'Словения'),
(uuid_generate_v1(), 'Соединённые Штаты Америки'),
(uuid_generate_v1(), 'Соломоновы Острова'),
(uuid_generate_v1(), 'Сомали'),
(uuid_generate_v1(), 'Судан'),
(uuid_generate_v1(), 'Суринам'),
(uuid_generate_v1(), 'Сьерра-Леоне'),
(uuid_generate_v1(), 'Таджикистан'),
(uuid_generate_v1(), 'Таиланд'),
(uuid_generate_v1(), 'Танзания'),
(uuid_generate_v1(), 'Того'),
(uuid_generate_v1(), 'Тонга'),
(uuid_generate_v1(), 'Тринидад и Тобаго'),
(uuid_generate_v1(), 'Тувалу'),
(uuid_generate_v1(), 'Тунис'),
(uuid_generate_v1(), 'Туркменистан'),
(uuid_generate_v1(), 'Турция'),
(uuid_generate_v1(), 'Уганда'),
(uuid_generate_v1(), 'Узбекистан'),
(uuid_generate_v1(), 'Украина'),
(uuid_generate_v1(), 'Уругвай'),
(uuid_generate_v1(), 'Федеративные Штаты Микронезии'),
(uuid_generate_v1(), 'Фиджи'),
(uuid_generate_v1(), 'Филиппины'),
(uuid_generate_v1(), 'Финляндия'),
(uuid_generate_v1(), 'Франция'),
(uuid_generate_v1(), 'Хорватия'),
(uuid_generate_v1(), 'Центральноафриканская Республика'),
(uuid_generate_v1(), 'Чад'),
(uuid_generate_v1(), 'Черногория'),
(uuid_generate_v1(), 'Чехия'),
(uuid_generate_v1(), 'Чили'),
(uuid_generate_v1(), 'Швейцария'),
(uuid_generate_v1(), 'Швеция'),
(uuid_generate_v1(), 'Эквадор'),
(uuid_generate_v1(), 'Экваториальная Гвинея'),
(uuid_generate_v1(), 'Эритрея'),
(uuid_generate_v1(), 'Эсватини'),
(uuid_generate_v1(), 'Эстония'),
(uuid_generate_v1(), 'Эфиопия'),
(uuid_generate_v1(), 'Южно-Африканская Республика'),
(uuid_generate_v1(), 'Южный Судан'),
(uuid_generate_v1(), 'Ямайка'),
(uuid_generate_v1(), 'Япония');