server:
  port: 8284

spring:
  application:
    name: rococo-painting
  datasource:
    url: 'jdbc:postgresql://localhost:5432/rococo-painting'
    username: postgres
    password: secret
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: public
    locations: classpath:db/migration/rococo-painting

rococo-artist:
  base-uri: http://localhost:8282

rococo-museum:
  base-uri: http://localhost:8289

logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: local
  autoconfigure:
    exclude:
      - org.springframework.cloud.vault.config.VaultAutoConfiguration
      - org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration
      - org.springframework.cloud.vault.config.VaultObservationAutoConfiguration
