version: '3.8'

services:
  rococo-all-db:
    container_name: rococo-all-db
    image: postgres:15.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - CREATE_DATABASES=rococo-auth,rococo-artist,rococo-userdata,rococo-museum,rococo-painting
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/script/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - 5432:5432
    command: ["postgres", "-c", "max_prepared_transactions=100"]
    networks:
      - rococo-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 3s
      timeout: 3s
      retries: 5

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.3.2
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - 2181:2181
    networks:
      - rococo-network

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.3.2
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
    ports:
      - 9092:9092
    networks:
      - rococo-network

  rococo-client:
    container_name: rococo-client
    build:
      context: ./rococo-client
      dockerfile: Dockerfile
      args:
        NPM_COMMAND: build:dev
    networks:
      - rococo-network
    depends_on:
      - kafka
      - rococo-all-db

volumes:
  pgdata:

networks:
  rococo-network:
    driver: bridge